### PR TITLE
fix(moo-ds): repair type-check in the tests, and run it in CI

### PR DESCRIPTION
**Pull request by AndrewMcLachlan**
`npm run type-check` currently **fails on `main`** with three errors, all in test files I added in #679 and #686. This fixes them and adds the CI step that would have caught them.

## Why nothing caught it

**CI never type-checked anything.** vitest runs through esbuild, which strips types without checking them, and the build compiles `src` while excluding tests. So a test file could stop compiling and every check stayed green.

That's structural, not bad luck — the same thing happened in #671.

**Demonstrated rather than asserted.** Reinstating one of the errors:

```
npm run type-check   ->  exit 1   Cannot find name 'afterEach'
vitest Modal.test    ->  35 passed
```

Tests alone could not have caught it.

## The three errors

| error | cause |
|---|---|
| `Cannot find name 'afterEach'` | The edit that added the block checked whether the file already mentioned `afterEach` before adding the import — and it did, **in the block being added**. |
| `Unused '@ts-expect-error'` | `popover` is a legitimate `HTMLAttribute`, so passing it was never a type error. |
| `Resolver<Values>` not assignable | TypeScript unified the resolver's two returns into one union, giving the success branch an `errors` of `{ name?: undefined }` where `ResolverSuccess` wants `Record<string, never>`. |

The second is worth a note: the directive being unused *reinforces* the test. `popover` is a prop a consumer really can pass — which is exactly why the component has to win. The comment now says that, rather than asserting a type error that never existed.

The third is fixed by annotating the return type so each branch is checked on its own, rather than by casting.

## CI change

`npm run type-check` runs **before** the tests, so a type error fails fast.

`type-check` is also extended to cover **demoo**, which it didn't before. demoo holds the Dashboard, validation and overlay samples, and was the one workspace nothing checked automatically — the same silent-breakage class this closes. It's currently clean, so this adds a guard rather than a backlog.

## Verification

- `npm run type-check` — **exit 0** (was exit 1 on `main`), now covering all four workspaces
- `npm run build` — all four packages clean
- `npm run test:run` — 1737/1737 pass

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: moo-ds/src/components/__tests__/Modal.test.tsx [hunk 1]
```diff
@@ -244,8 +244,9 @@ describe('Modal', () => {
         value: function () { }, configurable: true, writable: true,
       });
 
+      // popover is a valid HTMLAttribute, so this is a legitimate prop a
+      // consumer could pass -- which is exactly why the component has to win.
```
[the remark this answers is not in the document]
Comment (AndrewMcLachlan) [reply moo-ds/src/components/__tests__/Modal.test.tsx]: Agreed — "a valid HTMLAttribute" reads as though there were a type by that name.

Reworded: `popover` is a real HTML attribute, and it reaches the component because `ModalProps` extends `React.HTMLAttributes`. That is precisely why a consumer can pass it, and why the component has to win.

Fixed in 726c0c2.
